<?php
// module/Album/view/album/album/add.phtml:

$title = 'Marketing Performance';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
    <tr>
        <th>Campaign</th>
        <th>Registrations</th>
        <th>Revenue</th>
    </tr>
    <?php foreach ($campaigns as $campaign) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($campaign->name); ?></td>
            <td><?php echo $this->escapeHtml($campaign->regs); ?></td>
            <td><?php if (is_null($campaign->revenue)) {
                    echo "0";
                } else {
                    echo $this->escapeHtml($campaign->revenue);
                }; ?>€
            </td>
        </tr>
    <?php endforeach; ?>
</table>






